### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by raviroshanmehta** [yonathan06/fastify-typescript-starter#5]
I am getting the below error when running it on my windows development machine.  I have checked it with nodejs 18, 14, and 10.  each version has the same issue. can anyone please help?

C:\projects\fastify-app\my-server>npm run dev

> fastify-typescript-starter@1.5.0 dev
> nodemon | pino-pretty --colorize

[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\* tsconfig.json .env
[nodemon] watching extensions: ts
[nodemon] starting `npm run build && npm start`

> fastify-typescript-starter@1.5.0 build
> esbuild `find src \( -name '*.ts' \)` --platform=node --outdir=build --resolve-extensions=.js

X [ERROR] Invalid build flag: "-name"

1 error
node:child_process:910
    throw err;
    ^

Error: Command failed: C:\projects\fastify-app\my-server\node_modules\esbuild-windows-64\esbuild.exe `find src \( -name '*.ts' \)` --platform=node --outdir=build --resolve-extensions=.js
    at checkExecSyncError (node:child_process:871:11)
    at Object.execFileSync (node:child_process:907:15)
    at Object.<anonymous> (C:\projects\fastify-app\my-server\node_modules\esbuild\bin\esbuild:177:28)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12212,
  stdout: null,
  stderr: null
}

Node.js v18.8.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by yonathan06** [comment]
works fine on my machine
can you provide more details? what os do you use?

**Comment by raviroshanmehta** [comment]
I am using a windows machine. 

Below is the machine information - 

Edition	Windows 11 Home Single Language
Version	21H2
Installed on	‎09-‎10-‎2021
OS build	22000.856
Experience	Windows Feature Experience Pack 1000.22000.856.0

**Comment by yonathan06** [comment]
I didn't test it in windows, but I highly recommend using WSL https://docs.microsoft.com/en-us/windows/wsl/install or git bash for windows, because windows alone doesn't support bash
