### ISSUE TITLE
Need instructions on how to start in the docker

### ISSUE THREAD

**Issue by romanesko** [yonathan06/fastify-typescript-starter#8]
To start the process in docker, you must first install pnpm locally, then install packages through it (to create pnpm-lock.yaml) and only after that you can start docker (and it is also important not to forget to create an .env.something file and pass this something as an APP_ENV environment variable)

**Comment by yonathan06** [comment]
Regarding the pnpm local installation, it is mentioned
regarding running the docker, you are right, you need to create .env.{NODE_ENV} and build docker with --build-arg. this is mentioned in the package.json
